load(":rust/cargo_test.bzl", "cargo_api_tests")

package(default_visibility = ["//visibility:public"])

exports_files([
    "README.md",
    "cargo_defs.bzl",
    "defs.bzl",
    "extensions.bzl",
    "repositories.bzl",
    "rust/audit.bzl",
    "rust/cargo.bzl",
    "rust/cargo_test.bzl",
    "rust/defs.bzl",
    "rust/oci.bzl",
    "rust/transitions.bzl",
])

platform(
    name = "linux_amd64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

cargo_api_tests()

platform(
    name = "linux_arm64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
)
