load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load(":oci/config_test.bzl", "oci_config_tests")
load(":oci/macro_test.bzl", "oci_macro_tests")

package(default_visibility = ["//visibility:public"])

exports_files([
    "README.md",
    "defs.bzl",
    "extensions.bzl",
    "repositories.bzl",
    "k8s/defs.bzl",
    "oci/config.bzl",
    "oci/defs.bzl",
    "oci/macro_test.bzl",
])

oci_config_tests()

oci_macro_tests()

sh_binary(
    name = "k8s_apply_helper",
    srcs = ["k8s/k8s_apply_helper.sh"],
)
