"""Cargo-inferred wrappers for rules_rust targets generated by rules_rs.

Consumers bind one rules_rs-generated `aliases` / `all_crate_deps` pair with
`cargo_package(...)`. The public target macros then infer every Cargo edge,
including workspace path dependencies and proc macros, from Cargo.lock.
"""

load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_proc_macro", "rust_test")

def cargo_package(
        aliases_fn = None,
        all_crate_deps_fn = None,
        package_name = ""):
    """Binds a rules_rs-generated dependency repository to a BUILD package."""
    return struct(
        aliases_fn = aliases_fn,
        all_crate_deps_fn = all_crate_deps_fn,
        package_name = package_name,
    )

def _resolved_package_name(package_name, cargo = None):
    if package_name:
        return package_name
    if cargo != None and getattr(cargo, "package_name", ""):
        return cargo.package_name
    return native.package_name()

def _resolved_fn(explicit, cargo, field):
    if explicit != None:
        return explicit
    if cargo != None and hasattr(cargo, field):
        return getattr(cargo, field)
    return None

def _merged(*values):
    result = []
    for value in values:
        result.extend(value or [])
    return result

def _with_manifest_compile_data(kwargs, include_manifest_compile_data):
    out = dict(kwargs)
    if include_manifest_compile_data:
        out["compile_data"] = _merged(out.pop("compile_data", []), native.glob(["Cargo.toml"]))
    return out

def _with_inferred_aliases(kwargs, aliases_fn, cargo, package_name):
    out = dict(kwargs)
    if out.get("aliases") != None:
        return out

    inferred = cargo_aliases(
        aliases_fn = aliases_fn,
        cargo = cargo,
        package_name = package_name,
    )
    if inferred != None:
        out["aliases"] = inferred
    return out

def cargo_aliases(
        aliases_fn = None,
        package_name = "",
        cargo = None,
        **_legacy_selectors):
    """Returns the rules_rs alias map for the selected Cargo package."""
    resolved = _resolved_fn(aliases_fn, cargo, "aliases_fn")
    if resolved == None:
        return None
    return resolved(package_name = _resolved_package_name(package_name, cargo))

def cargo_all_crate_deps(
        all_crate_deps_fn = None,
        package_name = "",
        cargo = None,
        normal = True,
        normal_dev = False,
        build = False,
        cargo_only = False,
        proc_macro = False,
        proc_macro_dev = False):
    """Returns direct deps using the exact rules_rs generated selector API.

    `proc_macro` and `proc_macro_dev` are accepted for source compatibility
    with the former crate_universe facade. rules_rs includes proc macros in the
    ordinary dependency sets, so those flags fold into normal/normal_dev.
    """
    resolved = _resolved_fn(all_crate_deps_fn, cargo, "all_crate_deps_fn")
    if resolved == None:
        return []

    return resolved(
        normal = normal or proc_macro,
        normal_dev = normal_dev or proc_macro_dev,
        build = build,
        package_name = _resolved_package_name(package_name, cargo),
        cargo_only = cargo_only,
    )

def cargo_proc_macro_deps(
        all_crate_deps_fn = None,
        package_name = "",
        cargo = None,
        include_dev_deps = False):
    """Compatibility helper; rules_rs represents proc macros in normal deps."""
    return cargo_all_crate_deps(
        all_crate_deps_fn = all_crate_deps_fn,
        package_name = package_name,
        cargo = cargo,
        normal = True,
        normal_dev = include_dev_deps,
    )

def _inferred_deps(
        all_crate_deps_fn,
        cargo,
        package_name,
        include_dev_deps,
        include_dev_proc_macro_deps):
    return cargo_all_crate_deps(
        all_crate_deps_fn = all_crate_deps_fn,
        cargo = cargo,
        package_name = package_name,
        normal = True,
        normal_dev = include_dev_deps or include_dev_proc_macro_deps,
    )

def _rust_target(
        implementation,
        name,
        deps,
        bazel_deps,
        proc_macro_deps,
        cargo,
        aliases_fn,
        package_name,
        include_dev_deps,
        include_dev_proc_macro_deps,
        include_manifest_compile_data,
        all_crate_deps_fn,
        cargo_deps,
        cargo_macro_deps,
        kwargs):
    implementation(
        name = name,
        deps = _merged(
            deps,
            bazel_deps,
            _inferred_deps(
                all_crate_deps_fn = all_crate_deps_fn,
                cargo = cargo,
                package_name = package_name,
                include_dev_deps = include_dev_deps,
                include_dev_proc_macro_deps = include_dev_proc_macro_deps,
            ),
            cargo_deps,
        ),
        proc_macro_deps = _merged(proc_macro_deps, cargo_macro_deps),
        **_with_inferred_aliases(
            _with_manifest_compile_data(kwargs, include_manifest_compile_data),
            aliases_fn = aliases_fn,
            cargo = cargo,
            package_name = package_name,
        )
    )

def cargo_rust_library(
        name,
        deps = None,
        bazel_deps = None,
        proc_macro_deps = None,
        cargo = None,
        aliases_fn = None,
        package_name = "",
        include_dev_deps = False,
        include_dev_proc_macro_deps = False,
        include_manifest_compile_data = True,
        all_crate_deps_fn = None,
        cargo_deps = None,
        cargo_macro_deps = None,
        **kwargs):
    """Declares a rust_library whose Cargo dependencies are inferred."""
    _rust_target(
        implementation = rust_library,
        name = name,
        deps = deps,
        bazel_deps = bazel_deps,
        proc_macro_deps = proc_macro_deps,
        cargo = cargo,
        aliases_fn = aliases_fn,
        package_name = package_name,
        include_dev_deps = include_dev_deps,
        include_dev_proc_macro_deps = include_dev_proc_macro_deps,
        include_manifest_compile_data = include_manifest_compile_data,
        all_crate_deps_fn = all_crate_deps_fn,
        cargo_deps = cargo_deps,
        cargo_macro_deps = cargo_macro_deps,
        kwargs = kwargs,
    )

def cargo_rust_binary(
        name,
        deps = None,
        bazel_deps = None,
        proc_macro_deps = None,
        cargo = None,
        aliases_fn = None,
        package_name = "",
        include_dev_deps = False,
        include_dev_proc_macro_deps = False,
        include_manifest_compile_data = True,
        all_crate_deps_fn = None,
        cargo_deps = None,
        cargo_macro_deps = None,
        **kwargs):
    """Declares a rust_binary whose Cargo dependencies are inferred."""
    _rust_target(
        implementation = rust_binary,
        name = name,
        deps = deps,
        bazel_deps = bazel_deps,
        proc_macro_deps = proc_macro_deps,
        cargo = cargo,
        aliases_fn = aliases_fn,
        package_name = package_name,
        include_dev_deps = include_dev_deps,
        include_dev_proc_macro_deps = include_dev_proc_macro_deps,
        include_manifest_compile_data = include_manifest_compile_data,
        all_crate_deps_fn = all_crate_deps_fn,
        cargo_deps = cargo_deps,
        cargo_macro_deps = cargo_macro_deps,
        kwargs = kwargs,
    )

def cargo_rust_proc_macro(
        name,
        deps = None,
        bazel_deps = None,
        proc_macro_deps = None,
        cargo = None,
        aliases_fn = None,
        package_name = "",
        include_dev_deps = False,
        include_dev_proc_macro_deps = False,
        include_manifest_compile_data = True,
        all_crate_deps_fn = None,
        cargo_deps = None,
        cargo_macro_deps = None,
        **kwargs):
    """Declares a rust_proc_macro whose Cargo dependencies are inferred."""
    _rust_target(
        implementation = rust_proc_macro,
        name = name,
        deps = deps,
        bazel_deps = bazel_deps,
        proc_macro_deps = proc_macro_deps,
        cargo = cargo,
        aliases_fn = aliases_fn,
        package_name = package_name,
        include_dev_deps = include_dev_deps,
        include_dev_proc_macro_deps = include_dev_proc_macro_deps,
        include_manifest_compile_data = include_manifest_compile_data,
        all_crate_deps_fn = all_crate_deps_fn,
        cargo_deps = cargo_deps,
        cargo_macro_deps = cargo_macro_deps,
        kwargs = kwargs,
    )

def cargo_rust_test(
        name,
        deps = None,
        bazel_deps = None,
        proc_macro_deps = None,
        cargo = None,
        aliases_fn = None,
        package_name = "",
        include_dev_deps = True,
        include_dev_proc_macro_deps = True,
        include_manifest_compile_data = True,
        all_crate_deps_fn = None,
        cargo_deps = None,
        cargo_macro_deps = None,
        **kwargs):
    """Declares a rust_test whose Cargo dev dependencies are inferred."""
    _rust_target(
        implementation = rust_test,
        name = name,
        deps = deps,
        bazel_deps = bazel_deps,
        proc_macro_deps = proc_macro_deps,
        cargo = cargo,
        aliases_fn = aliases_fn,
        package_name = package_name,
        include_dev_deps = include_dev_deps,
        include_dev_proc_macro_deps = include_dev_proc_macro_deps,
        include_manifest_compile_data = include_manifest_compile_data,
        all_crate_deps_fn = all_crate_deps_fn,
        cargo_deps = cargo_deps,
        cargo_macro_deps = cargo_macro_deps,
        kwargs = kwargs,
    )

def _sanitize_target_name(value):
    sanitized = value
    for ch in ["/", "\\", ".", "-", ":", "@"]:
        sanitized = sanitized.replace(ch, "_")
    return sanitized

def cargo_rust_test_suite(
        name,
        srcs,
        shared_srcs = None,
        tags = None,
        visibility = None,
        testonly = None,
        **kwargs):
    """Creates one Cargo-inferred rust_test per integration-test source."""
    shared_srcs = list(shared_srcs or [])
    shared_srcs_set = {src: True for src in shared_srcs}
    test_tags = list(tags or [])
    generated_tests = []

    for src in srcs:
        if type(src) != "string":
            fail("cargo_rust_test_suite only supports string labels, got {}".format(src))
        if src in shared_srcs_set or not src.endswith(".rs"):
            continue

        target = "{}__{}".format(name, _sanitize_target_name(src))
        cargo_rust_test(
            name = target,
            srcs = [src] + shared_srcs,
            tags = test_tags,
            **kwargs
        )
        generated_tests.append(":" + target)

    if not generated_tests:
        fail("cargo_rust_test_suite({}, ...) found no Rust test sources".format(name))

    suite_kwargs = {
        "name": name,
        "tests": generated_tests,
        "tags": test_tags,
    }
    if visibility != None:
        suite_kwargs["visibility"] = visibility
    if testonly != None:
        suite_kwargs["testonly"] = testonly
    native.test_suite(**suite_kwargs)
